name: Depandabot Workflow
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Dependabot
        uses: dependabot/fetch-metadata@v2
        with:
          package-ecosystem: "npm"
          directory: "/"
          target-branch: "main"