name: workflow dispatcher
on: 
  workflow_dispatch:
    inputs:
        environment:
          description: 'Select any environment to deploy'
          required: true
          default: 'dev'
          type: choice
          options:
            - staging
            - production
        version:
          description: 'Enter the version to deploy'
          required: true
          default: '1.0.0'

jobs:
  manual-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run manual workflow
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"