name: workflow dispatcher
on: 
  workflow_dispatch:
    inputs:
        environment:
            description: 'Select the environment'
            required: true
            default: 'dev'
            type: choice
            options:
                - staging
                - production
        version:
            description: 'Specify the version'
            required: true
            default: '1.0.0'
            type: string

jobs:
  manual-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run manual workflow
        run: |
          echo "Running manual workflow with environment: ${{ github.event.inputs.environment }} and version: ${{ github.event.inputs.version }}"