name: workflow dispatcher
on: 
  push:

jobs:
  manual-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run manual workflow
        run: |
          echo "This is a manual workflow triggered by a push event."